# before/app/services/package_service.py — ISP violation
class PackageRepository:
    """A 12-method repository. CreatePackage uses ONE."""
    def __init__(self, session): self._session = session

    def add(self, package): ...                    # ← uso único do CreatePackage
    def by_id(self, package_id): ...
    def list(self): ...
    def update(self, package): ...
    def delete(self, package_id): ...
    def find_by_destination(self, destination): ...
    def find_by_price_range(self, lo, hi): ...
    def paginated(self, page, size=10): ...
    def count_by_traveler(self, traveler_id): ...
    def upsert(self, package): ...
    def archive(self, package_id): ...
    def bulk_insert(self, packages): ...


# Um fake pra testar CreatePackage precisa implementar os 12...
class FakePackageRepository:
    def add(self, p): self.last = p
    def by_id(self, id): raise NotImplementedError
    def list(self): raise NotImplementedError
    def update(self, p): raise NotImplementedError
    def delete(self, id): raise NotImplementedError
    def find_by_destination(self, d): raise NotImplementedError
    # ... mais 6 NotImplementedError
